CREATE
OR REPLACE PROCEDURE DUMMY (
    INOUT programm CHAR(20),
    INOUT Fehlernummer dec(5, 0),
    INOUT Fehlertext CHAR(100),
    INOUT Programmnummer dec(7, 0),
    INOUT xmldaten varchar(32000),
    INOUT traceId CHAR(36) DEFAULT '',
    INOUT runAsUserId CHAR(10) DEFAULT ''
) LANGUAGE RPGLE SPECIFIC DUMMY NOT DETERMINISTIC MODIFIES SQL DATA CALLED ON NULL INPUT PARAMETER STYLE SQL